import type { Course, LiveSession, Profile, QaReview, Review } from "@shared/types";

export const CURRENT_USER_ID = "t1";

// A fixed reference point (not Date.now()) so every relative mock timestamp
// below renders identically on the server and after client hydration —
// Date.now() at module scope drifts between the two and breaks hydration.
const NOW = new Date("2026-08-25T12:00:00Z").getTime();

export const mockTutors: Profile[] = [
  {
    id: "t1",
    fullName: "Maya Chen",
    role: "tutor",
    ageBracket: "18_plus",
    parentalConsentGiven: true,
    bio: "Senior at Lincoln High. Tutoring AP Calculus BC and Algebra II for 2 years.",
    isIdVerified: true,
    ratingAvg: 4.9,
    ratingCount: 62,
  },
  {
    id: "t2",
    fullName: "Jordan Patel",
    role: "tutor",
    ageBracket: "18_plus",
    parentalConsentGiven: true,
    bio: "CS sophomore at State University. Loves teaching Python to beginners.",
    isIdVerified: true,
    ratingAvg: 4.8,
    ratingCount: 41,
  },
  {
    id: "t3",
    fullName: "Aisha Rahman",
    role: "tutor",
    ageBracket: "13_to_17",
    parentalConsentGiven: true,
    bio: "Junior, National Chemistry Olympiad qualifier. Teaches AP Chemistry.",
    isIdVerified: false,
    ratingAvg: 4.7,
    ratingCount: 23,
  },
  {
    id: "t4",
    fullName: "Diego Morales",
    role: "tutor",
    ageBracket: "18_plus",
    parentalConsentGiven: true,
    bio: "Native Spanish speaker, freshman at State University, tutors Spanish I & II.",
    isIdVerified: true,
    ratingAvg: 5.0,
    ratingCount: 18,
  },
];

export const mockCourses: Course[] = [
  {
    id: "c1",
    tutorId: "t1",
    tutorName: "Maya Chen",
    subject: "AP Calculus BC",
    title: "AP Calculus BC: From Limits to Series",
    description:
      "A full walkthrough of the AP Calc BC curriculum, taught the way I wish someone had taught it to me — lots of worked examples, common mistakes flagged along the way.",
    priceCents: 4500,
    status: "published",
    lessonCount: 24,
    totalDurationMinutes: 380,
    ratingAvg: 4.9,
    ratingCount: 51,
    enrollmentCount: 312,
    createdAt: new Date(NOW - 1000 * 60 * 60 * 24 * 200).toISOString(),
  },
  {
    id: "c2",
    tutorId: "t2",
    tutorName: "Jordan Patel",
    subject: "Intro to Python",
    title: "Python From Zero: Build 5 Small Projects",
    description:
      "No experience needed. We build a calculator, a to-do list, a quiz game, a simple web scraper, and a Discord bot.",
    priceCents: 3000,
    status: "published",
    lessonCount: 18,
    totalDurationMinutes: 260,
    ratingAvg: 4.8,
    ratingCount: 34,
    enrollmentCount: 201,
  },
  {
    id: "c3",
    tutorId: "t3",
    tutorName: "Aisha Rahman",
    subject: "AP Chemistry",
    title: "AP Chemistry Crash Course: Unit 1-4",
    description: "Covers atomic structure, bonding, stoichiometry, and gas laws with practice FRQs.",
    priceCents: 2500,
    status: "pending_review",
    lessonCount: 12,
    totalDurationMinutes: 150,
    ratingAvg: 0,
    ratingCount: 0,
    enrollmentCount: 0,
  },
  {
    id: "c4",
    tutorId: "t4",
    tutorName: "Diego Morales",
    subject: "Spanish I",
    title: "Conversational Spanish I: Speak From Day One",
    description: "Focused on speaking and listening, not just grammar drills.",
    priceCents: 2000,
    status: "published",
    lessonCount: 15,
    totalDurationMinutes: 190,
    ratingAvg: 5.0,
    ratingCount: 12,
    enrollmentCount: 88,
    createdAt: new Date(NOW - 1000 * 60 * 60 * 24 * 120).toISOString(),
  },
  {
    id: "c5",
    tutorId: "t1",
    tutorName: "Maya Chen",
    subject: "AP Calculus AB",
    title: "AP Calculus AB: Derivatives Deep Dive",
    description: "A focused course on differentiation rules, implicit differentiation, and related rates, with FRQ practice.",
    priceCents: 3500,
    status: "published",
    lessonCount: 14,
    totalDurationMinutes: 210,
    ratingAvg: 4.8,
    ratingCount: 9,
    enrollmentCount: 47,
    createdAt: new Date(NOW - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
];

export const mockLiveSessions: LiveSession[] = [
  {
    id: "s1",
    tutorId: "t1",
    tutorName: "Maya Chen",
    subject: "AP Calculus BC",
    title: "1:1 Help — Related Rates & Optimization",
    description: "Bring your homework or a specific topic you're stuck on.",
    priceCents: 3500,
    scheduledAt: new Date(NOW + 1000 * 60 * 60 * 26).toISOString(),
    durationMinutes: 45,
    maxParticipants: 1,
    bookedCount: 0,
    status: "scheduled",
    joinUrl: "https://meet.peerscholar.app/s1",
  },
  {
    id: "s2",
    tutorId: "t2",
    tutorName: "Jordan Patel",
    subject: "Intro to Python",
    title: "Group Session — Debugging Your Project",
    description: "Small group (up to 4). Bring your code, we'll debug together.",
    priceCents: 1500,
    scheduledAt: new Date(NOW + 1000 * 60 * 60 * 50).toISOString(),
    durationMinutes: 60,
    maxParticipants: 4,
    bookedCount: 2,
    status: "scheduled",
    joinUrl: "https://meet.peerscholar.app/s2",
  },
  {
    id: "s3",
    tutorId: "t4",
    tutorName: "Diego Morales",
    subject: "Spanish I",
    title: "Conversation Practice Hour",
    description: "Casual conversation practice, all levels welcome.",
    priceCents: 1200,
    scheduledAt: new Date(NOW + 1000 * 60 * 60 * 8).toISOString(),
    durationMinutes: 60,
    maxParticipants: 6,
    bookedCount: 5,
    status: "scheduled",
    joinUrl: "https://meet.peerscholar.app/s3",
  },
  {
    id: "s4",
    tutorId: "t1",
    tutorName: "Maya Chen",
    subject: "AP Calculus BC",
    title: "Live Review — Series Convergence Tests",
    description: "Walking through the ratio, root, and comparison tests with practice problems.",
    priceCents: 0,
    scheduledAt: new Date(NOW + 1000 * 60 * 60 * 4).toISOString(),
    durationMinutes: 50,
    maxParticipants: 30,
    bookedCount: 21,
    status: "scheduled",
    joinUrl: "https://meet.peerscholar.app/s4",
  },
];

// Last 6 weeks of gross earnings for the signed-in tutor (t1), used by the
// analytics chart on the Teach dashboard.
export const mockEarningsHistory = [
  { label: "Wk 1", cents: 18400 },
  { label: "Wk 2", cents: 21200 },
  { label: "Wk 3", cents: 19800 },
  { label: "Wk 4", cents: 26500 },
  { label: "Wk 5", cents: 31200 },
  { label: "Wk 6", cents: 29700 },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    reviewerId: "u1",
    reviewerName: "Sam K.",
    targetType: "tutor",
    targetId: "t1",
    rating: 5,
    comment: "Maya explained series convergence better than my actual teacher. Highly recommend.",
    createdAt: new Date(NOW - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "r2",
    reviewerId: "u2",
    reviewerName: "Priya N.",
    targetType: "course",
    targetId: "c1",
    rating: 5,
    comment: "Watched this before my AP exam, went from a 3 to a 5 on my practice test after.",
    createdAt: new Date(NOW - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
];

export const mockQaQueue: QaReview[] = [
  {
    id: "qa1",
    qaReviewerId: "qa-self",
    targetType: "course",
    targetId: "c3",
    targetTitle: "AP Chemistry Crash Course: Unit 1-4",
    rubricScore: {},
    passed: false,
    notes: "",
    reviewedAt: "",
  },
];
